### ISSUE TITLE
route.routeName is undefined : with fix.

### ISSUE THREAD

**Issue by tuddman** [jm90m/expo-netflix-example#1]
Great example + tutorial. Thanks!

I had an issue with getting it to render properly, if anyone comes across the same issue:

I was getting an `route.routeName is undefined`  error when trying to load it with expo.

I was able to track down discussion of the issue [here](https://github.com/react-navigation/react-navigation/issues/3148#issuecomment-352778884)

I set  in `App.js` 
```
const drawerNavigatorConfig = {
  contentComponent: props => <CustomDrawerContentComponent {...props}/>,
  drawerOpenRoute: 'DrawerOpen',  
  drawerCloseRoute: 'DrawerClose',
  drawerToggleRoute: 'DrawerToggle'

};
```

for the app to load properly.

**Comment by jm90m** [comment]
thanks for bringing this issue up @tuddman 

I haven't touched this repo in a long time, so not too sure if it works with new versions of expo / react native / react navigation
